### ISSUE TITLE
Создание модуля верхнего уровня и временных ограничений

### ISSUE THREAD

**Issue by Elesv** [OpticalMeasurementsSystems/VideoControlIP#11]

**Comment by Elesv** [comment]
Модуль создан, то есть первая подзадача - закрыта. Что касается констрэйнтов, у меня возникли некоторые проблемы.

Я думаю в первую очередь нужно уточнить выходную частоту clock_divider_0, в данный момент делитель равен 5 (20МГц, учитывая что фабрик равен 100МГц), хотя в констрейнте я указал 50МГц.

![clock_divider_0_freq](https://cloud.githubusercontent.com/assets/20006020/21505741/0380eb4a-cc8c-11e6-818a-36f7aed00401.png)

**Comment by Elesv** [comment]
Некоторое время назад я упоминал что Вивада имеет тенденцию блокировать свойства пинов по своему выбору. Это - вторая проблема. Ниже я прикрепил скриншот окна свойств пина main_clock linescanner_image_capture_unit_0.

![linescanner_image_capture_unit_0_auto_property](https://cloud.githubusercontent.com/assets/20006020/21505835/c6625e8c-cc8c-11e6-95a4-521e160f1c3f.png)

**Comment by Elesv** [comment]
А вот окно свойств main_clock linescanner_image_capture_unit_1, где все свойства свободно редактируются.

![linescanner_image_capture_unit_1_no_auto](https://cloud.githubusercontent.com/assets/20006020/21505889/596021ba-cc8d-11e6-9cd3-436886d0cab5.png)

**Comment by Elesv** [comment]
Не помогает ни валидация(которая по всей видимости работает как апдейт), ни редактирование файлов руками.

**Comment by Elesv** [comment]
Есть и другие проблемы. Я пока не знаю как их решить.

![image](https://cloud.githubusercontent.com/assets/20006020/21511814/4835ad3a-ccc7-11e6-9422-ee2460a5db33.png)

**Comment by EvilLord666** [comment]
Думаю, что эту задачу можно закрыть т.к. и враппер и xdc у нас есть.
