### ISSUE TITLE
Модуль ядра Linux для взаимодействия с IP-ядром

### ISSUE THREAD

**Issue by EvilLord666** [OpticalMeasurementsSystems/VideoControlIP#13]
Сейчас, получилось так, что сырые данные в ПЛИС должны обрабатываться и в итоге мы должны получать пару чисел, что, с одной стороны, для нас проще и удобнее, но теперь также появилось требование иметь модуль ядра PetaLinux (http://www.wiki.xilinx.com/PetaLinux) для передачи этих данных в приложение, запускемое из под ОС, кроме того, нужно из этого приложения проводить конфигурирование нашей системы.  Наши модули зацеплены на шины AXI и AXI LIte.

Само управление линейными сканерами зацеплено на AXI QUAD SPI (согласно, https://www.xilinx.com/support/documentation/ip_documentation/axi_quad_spi/v3_2/pg153-axi-quad-spi.pdf для него существует драйвер для Linux). Однако, у нас есть модуль для общего управления всем IP-ядром (image_capture_manager), он зацеплен на AXI Lite. Нужно понять а возможно ли управление всем нашим IP-ядром из-под Linux, возможно, существуют готовые драйвера.

Общая схема работы устройства описана на Wiki:

https://github.com/OpticalMeasurementsSystems/VideoControlIP/wiki/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC-%D0%B7%D0%B0%D1%85%D0%B2%D0%B0%D1%82%D0%B0-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9

Архитектура разрабатываемого IP-ядра

https://github.com/OpticalMeasurementsSystems/VideoControlIP/blob/master/docs/Architecture.jpg

**Comment by stdstring** [comment]
Xilinx drivers for Linux:
http://www.wiki.xilinx.com/Linux+Drivers

**Comment by stdstring** [comment]
Отсюда http://www.wiki.xilinx.com/DMA+Drivers+-+Soft+IPs:
> The AXI Direct Memory Access (AXI DMA) IP provides high-bandwidth direct memory access between memory and AXI4-Stream-type target peripherals. Its optional scatter gather capabilities also offload data movement tasks from the Central Processing Unit (CPU) in processor based systems. Initialization, status, and management registers are accessed through an AXI4-Lite slave interface.
Достаточно ли этого?

**Comment by stdstring** [comment]
Есть еще вот такое http://www.wiki.xilinx.com/AXI+GPIO:
> The Xilinx® LogiCORE™ IP AXI General Purpose Input/Output (GPIO) core provides a general purpose input/output interface to the AXI interface. This 32-bit soft Intellectual Property (IP) core is designed to interface with the AXI4-Lite interface.The AXI GPIO design provides a general purpose
input/output interface to an AXI4-Lite interface. The AXI GPIO can be configured as either a single or a dual-channel device. The width of each channel is independently configurable.
...
Supports the AXI4-Lite interface specification

Как насчет этого?

**Comment by stdstring** [comment]
http://www.wiki.xilinx.com/Linux+User+Mode+Pseudo+Driver
How to access some simple hardware from user space. Example

**Comment by stdstring** [comment]
По нашей проблеме
Есть вот такой драйвер:
> http://www.wiki.xilinx.com/DMA+Drivers+-+Soft+IPs
AXI DMA
The AXI Direct Memory Access (AXI DMA) IP provides high-bandwidth direct memory access between memory and AXI4-Stream-type target peripherals. Its optional scatter gather capabilities also offload data movement tasks from the Central Processing Unit (CPU) in processor based systems. Initialization, status, and management registers are accessed through an AXI4-Lite slave interface.

Есть такой драйвер:
> http://www.wiki.xilinx.com/AXI+GPIO
The Xilinx® LogiCORE™ IP AXI General Purpose Input/Output (GPIO) core provides a general purpose input/output interface to the AXI interface. This 32-bit soft Intellectual Property (IP) core is designed to interface with the AXI4-Lite interface.The AXI GPIO design provides a general purpose input/output interface to an AXI4-Lite interface.

Достаточно ли этого? Нужно обсуждение ...

**Comment by EvilLord666** [comment]
AXI GPIO как раз подойдет для управления image_capture_manager,
Для VDMA - Video4Linux
Для AXI Quad SPI -QSPI Driver

Драйвер псевдоустройства для быстрого старта штука неплохая, остается понять как на GPIO_BASE_ADDRESS мапится адресное пространство AXI.

**Comment by stdstring** [comment]
Это написано здесь: http://www.wiki.xilinx.com/Build+kernel
В частности, вот пример файла system.mhs со всеми оперделениями: https://www.xilinx.com/Attachment/system.mhs

**Comment by stdstring** [comment]
Подведем промежуточные итоги.
1) Использование драйвера псевдоустройства безопасно и вполне допустимо в рабочем коде (см. этот пример http://www.wiki.xilinx.com/Linux+User+Mode+Pseudo+Driver). При таком подходе мы обращаемся к определенным адресам физической памяти, закрепленным для доступа к некоторому устройству (эти адреса задаются при сборке ядра и во время выполнения фиксированы) при помощи проецирования в память файла /dev/mem.  Для этого нам нужны будут либо права root, либо настроить правила udev для некоторой УЗ.
2) В идеале, лучше все-таки сделать отдельный модуль ядра Linux для взаимодействия с IP-ядром. Но сделать это можно в самый последний момент. Поэтому на данный момент предлагаю использовать драйвер псевдоустройства.

**Comment by EvilLord666** [comment]
Проект заморожен, задача прекращается в связи со сворачиванием 218-го.
