### ISSUE TITLE
Идентификатор текущей записанной ячейке

### ISSUE THREAD

**Issue by EvilLord666** [OpticalMeasurementsSystems/VideoControlIP#16]
Мы работаем с памятью в циклическом режиме т.е. после достижения максимального адреса, например 0xFFFFFFFF, следующим адресом для записи становится 0х00000000, однако, если ранее были записаны какие либо данные, то мы не сможем грамотно отследить точку в которую сейчас осуществляется запись, т.е. необходимо данные выгребать буфером, например, по нескольку циклов записи + понимать где остановиться. Соответственно где-то должен осуществляться подсчет числа записанных ячеек (или в топовом модуле, или в самом AXI VIDEO DMA (если, такая возможность есть)).

**Comment by Elesv** [comment]
В VDMA предусмотрены соответствующие регистры под статус и конфигурацию.

**Comment by Elesv** [comment]
[AXI Video Direct Memory Access v6.2, стр. 16](https://www.xilinx.com/support/documentation/ip_documentation/axi_vdma/v6_2/pg020_axi_vdma.pdf)

**Comment by EvilLord666** [comment]
Проект заморожен, задача прекращается в связи со сворачиванием 218-го.
