### ISSUE TITLE
Модификация проекта

### ISSUE THREAD

**Issue by EvilLord666** [OpticalMeasurementsSystems/VideoControlIP#26]
Необходимо модифицировать дизайн проект и приложение под проц в соответствие с изменениями в 2DImageProcessor и QuickSPI после того, как QuickSPI будет завершен.

**Comment by EvilLord666** [comment]
Ребята-студенты, как у вас эта задача ? я так понимаю, что хорошо бы распараллелить: пока один из вас занят задачей #21, другой пусть занимается этой задачей.

**Comment by boyarincevAlex** [comment]
Я правильно понял, что нужно соединить 2DImageProcessor и QuickSPI в ImageCaptureSystem?

**Comment by EvilLord666** [comment]
Нужно сделать схему подключения IP-ядер /клоков/сбросов аналогичной схеме в проекте 2DImageProсessing, а SPI заменить также как и в 2DImageProсessing. В этом проекте и  2DImageProсessing отличаются только цепочки обработки данных в этом данные идут в вдма, в  2DImageProсessing - обрабатываются на лету.

**Comment by boyarincevAlex** [comment]
Решил не создавать отдельную ветку и закинул изменения в UshakovMV_ManyFixes. Нужно ли удалять делители частоты и сделать клоки от процессора, как в 2DImageProсessing, или оставить как есть?

**Comment by EvilLord666** [comment]
Конечно, лучше было бы использовать отдельную ветку, но раз сделал, тогда уж ладно. Клоки тоже лучше сделать как в том проекте, модули физически из src не удаляй,но клоки подцепи от процессора.

**Comment by boyarincevAlex** [comment]
Я решил в эту ветку залить, потому что там были последние изменения. Насчет резета вопрос, сделать как в 2DImageProсessing? Я просто не понял, чем отличается peripheral_aresetn и инвертированный peripheral_reset. И сишный код тоже надо переносить?

**Comment by EvilLord666** [comment]
По этому вопросу почитай описание ядра proc_reset_system_7.0, но по диаграммам, они отличаются только полярностью клока и идеологией использования: peripheral_aresetn - асинхронный, peripheral_reset - синхронный.

**Comment by EvilLord666** [comment]
С++ код также нужно модифицировать как в 2DImageProcessor

**Comment by EvilLord666** [comment]
Ребята, когда эта задача будет завершена?

**Comment by boyarincevAlex** [comment]
Нам не совсем понятен процессорный код С++, будем разбираться, думаю, через неделю справимся

**Comment by EvilLord666** [comment]
В другом проекте (2dimageprocessing) аналогичный процессорный код, но не идентичные, поэтому посмотрите как он устроен там. В целом вам нужно избавиться от QuadSpi. Дизайн проект полностью модифицирован?

**Comment by boyarincevAlex** [comment]
Почти да, осталось только внести изменения в резет.

**Comment by boyarincevAlex** [comment]
С quadspi сделать также как и в 2dimageprocessing через #ifdef? Что-нибудь еще нужно изменять?

**Comment by EvilLord666** [comment]
QuadSPI нужно удалить полностью.

**Comment by boyarincevAlex** [comment]
какие еще изменения нужно внести?

**Comment by EvilLord666** [comment]
Я проверю проект, когда вернусь в ЕКатеринбург в конце недели и отпишусь.

**Comment by EvilLord666** [comment]
1) Отсутствует aux_reset, нужна модификация image_capture_manager.v и, соответственно, процессорного кода для управления сбросом по AXI.
2) Модифицировать timing_constraints.xdc поскольку в обоих проектах тайминги должны быть одинаковыми.
3) Взять dragsterConfig из 2d_image_processing и заменить их в этом проекте, модифицировать остальную часть софтового проекта, чтобы проект компилировался.

**Comment by EvilLord666** [comment]
Проект заморожен, задача прекращается в связи со сворачиванием 218-го.
