### ISSUE TITLE
Проблемы дизайна в Vivado

### ISSUE THREAD

**Issue by EvilLord666** [OpticalMeasurementsSystems/VideoControlIP#7]
Назначал адреса для IP-ядер, подключаемых к AXI, все бы ничего, но валидация дизайна происходит только в том случае, если axi_vdma_0 и axi_vdma_1 проецируются в одну область памяти, видимо где-то есть проблема с дизайном или все же валидатор прав?
![adressquestion](https://cloud.githubusercontent.com/assets/18068522/19077559/32148bbc-8a5e-11e6-8e82-b7e6652cf587.png)

**Comment by Elesv** [comment]
Прошу прощения что поздно присоединяюсь. Мне кажется S_AXI_LITE у обоих VDMA лучше перецепить вот так:
![image](https://cloud.githubusercontent.com/assets/20006020/19094387/59c3d5e6-8aa9-11e6-9d6f-620fb5c397b5.png)

**Comment by Elesv** [comment]
Я бы хотел предложить задействовать еще один HP порт на PS и зацепить на него второй VDMA:
![image](https://cloud.githubusercontent.com/assets/20006020/19095921/3876e0e6-8ab2-11e6-8cf6-f5035d907d33.png)

**Comment by Elesv** [comment]
Что касается адресов, если они оба у нас по 64MB, то мне кажется первому можно присвоить 0x00000000(0)-0x03FFFFFF(67108863), а второму, сразу следующий выровненный диапазон(range) 0x04000000(67108864)-0x07FFFFFF(134217727)
![image](https://cloud.githubusercontent.com/assets/20006020/19096167/df1ed344-8ab3-11e6-8d09-41234dd61db0.png)

**Comment by Elesv** [comment]
На всякий случай, скриншот успешной валидации данного дизайна:
![image](https://cloud.githubusercontent.com/assets/20006020/19096450/f0062dae-8ab5-11e6-8389-36487eab6730.png)

**Comment by Elesv** [comment]
Ну и синтеза тоже:
![image](https://cloud.githubusercontent.com/assets/20006020/19096505/540ec96e-8ab6-11e6-8542-13d4d7f1926b.png)

**Comment by Elesv** [comment]
Хотя пара warning'ов у меня все же есть:
![image](https://cloud.githubusercontent.com/assets/20006020/19096537/9c826e12-8ab6-11e6-886a-c0a68e0ca135.png)

**Comment by EvilLord666** [comment]
Сейчас, все ок, спасибо Саш.
